import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:prototype_app_pang/font_family/font_style.dart';
import 'package:prototype_app_pang/main_menu/destroy/model/destroy_evidence.dart';
import 'package:prototype_app_pang/main_menu/stock/model/balance.dart';
import 'package:prototype_app_pang/main_menu/stock/model/balance_detail.dart';
import 'package:prototype_app_pang/main_menu/stock/model/balance_type.dart';
import 'package:prototype_app_pang/main_menu/stock/model/stock_main.dart';
import 'package:prototype_app_pang/main_menu/stock/stock_screen.dart';
import 'package:prototype_app_pang/model/test/Background.dart';

class StockFragment extends StatefulWidget {
  @override
  _FragmentState createState() => new _FragmentState();
}

class _FragmentState extends State<StockFragment> {
  //style content
  TextStyle textStyleLanding =
      TextStyle(fontSize: 20, fontFamily: FontStyles().FontFamily);
  TextStyle textStyleLabel = TextStyle(
      fontSize: 16,
      color: Color(0xff087de1),
      fontFamily: FontStyles().FontFamily);
  TextStyle textStyleData = TextStyle(
      fontSize: 18, color: Colors.black, fontFamily: FontStyles().FontFamily);
  TextStyle textStylePageName = TextStyle(
      color: Colors.grey[400],
      fontFamily: FontStyles().FontFamily,
      fontSize: 12.0);
  TextStyle textStyleDataSub =
      TextStyle(fontSize: 16, fontFamily: FontStyles().FontFamily);
  EdgeInsets paddingData = EdgeInsets.only(top: 4.0, bottom: 4.0);
  EdgeInsets paddingLabel = EdgeInsets.only(top: 4.0, bottom: 4.0);
  TextStyle textStyleButtonAccept = TextStyle(
      fontSize: 16, color: Colors.white, fontFamily: FontStyles().FontFamily);
  TextStyle textStyleButtonNotAccept = TextStyle(
      fontSize: 16,
      color: Color(0xff087de1),
      fontFamily: FontStyles().FontFamily);
  TextStyle textInputStyleTitle = TextStyle(
      fontSize: 16.0, color: Colors.black, fontFamily: FontStyles().FontFamily);

  //item data
  List<ItemsStockMain> itemMain = [
    new ItemsStockMain(
        "คลังเก็บสินค้าในส่วนกลาง",
        new ItemsStockBalance([
          new ItemsStockBalanceType(
              "ของกลางระหว่างคดี",
              "RC0807006200003",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200009",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    30,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200010",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    2)
              ],
              1),
          new ItemsStockBalanceType(
              "ของกลางระหว่างคดี",
              "RC0807006200003",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200009",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    30,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200010",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    3)
              ],
              1),
        ], [
          new ItemsStockBalanceType(
              "รอขายทอดตลาด",
              "BO0807006200002",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200009",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    30,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200010",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    2)
              ],
              2),
          new ItemsStockBalanceType(
              "รอทำลายของกลาง",
              "DT0807006200014",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2)
              ],
              2),
          new ItemsStockBalanceType(
              "รอจัดเก็บเข้าพิพิธภัณฑ์",
              "BO0807006200002",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2)
              ],
              2),
          new ItemsStockBalanceType(
              "รอคืนของกลาง",
              "RT0807006200002",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2)
              ],
              2),
        ], [
          new ItemsStockBalanceType(
              "รอคืนจากหน่วยงานภายนอก",
              "RT0807006200002",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200009",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    30,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200010",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200011",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200012",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    2)
              ],
              2),
        ])),
    new ItemsStockMain(
        "คลังเก็บสินค้าในส่วนกลางลำดับ 1",
        new ItemsStockBalance([
          new ItemsStockBalanceType(
              "ของกลางระหว่างคดี",
              "RC0807006200003",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200009",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    30,
                    "ลิตร",
                    3),
                new ItemsStockBalanceDetail(
                    "IN00107016200010",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    1)
              ],
              1),
          new ItemsStockBalanceType(
              "ของกลางเสร็จสิ้นคดี",
              "BO0807006200002",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    3)
              ],
              2),
        ], [
          new ItemsStockBalanceType(
              "รอขายทอดตลาด",
              "BO0807006200002",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200009",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    30,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200010",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    1)
              ],
              2),
        ], [
          new ItemsStockBalanceType(
              "รอคืนจากหน่วยงานภายนอก",
              "RT0807006200002",
              "2018-09-09",
              [
                new ItemsStockBalanceDetail(
                    "IN00107016200008",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    20,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200009",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    12,
                    "ชวด",
                    30,
                    "ลิตร",
                    2),
                new ItemsStockBalanceDetail(
                    "IN00107016200010",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    1),
                new ItemsStockBalanceDetail(
                    "IN00107016200011",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    3),
                new ItemsStockBalanceDetail(
                    "IN00107016200012",
                    "09 กันยายน 2561",
                    new ItemsDestroyEvidence(
                      "สุรา",
                      "สราแช่",
                      "ชนิดเบียร์",
                      "4.4",
                      "ดีกรี",
                      "hoegaarden",
                      "",
                      "SADLER S PEAKY BLINDER",
                      0,
                      "ลิตร",
                      0,
                      "",
                      0,
                      "",
                      false,
                      null,
                      false,
                      null,
                    ),
                    15,
                    "ชวด",
                    40,
                    "ลิตร",
                    2)
              ],
              2)
        ])),
  ];
      /*List<ItemsStockMain> itemMain = [
            new ItemsStockMain(
                "คลังเก็บสินค้าในส่วนกลาง",
                new ItemsStockBalance(
                    [
                          new ItemsStockBalanceType(
                              "ของกลางระหว่างคดี",
                              [
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200008",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200009",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        30,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200010",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        2)
                              ],
                              1),
                          new ItemsStockBalanceType(
                              "ของกลางระหว่างคดี",
                              [
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200008",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200009",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        30,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200010",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        3)
                              ],
                              1),
                    ],
                    [
                          new ItemsStockBalanceType(
                              "รอขายทอดตลาด",
                              [
                                    new ItemsStockBalanceDetail(
                                        "OU00107016200008",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "OU00107016200011",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        30,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "OU00107016200012",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        2)
                              ],
                              2),
                          new ItemsStockBalanceType(
                              "รอทำลายของกลาง",
                              [
                                    new ItemsStockBalanceDetail(
                                        "DT08070062000014",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2)
                              ],
                              2),
                          new ItemsStockBalanceType(
                              "รอจัดเก็บเข้าพิพิธภัณฑ์",
                              [
                                    new ItemsStockBalanceDetail(
                                        "RC00107016200008",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2)
                              ],
                              2),
                          new ItemsStockBalanceType(
                              "รอคืนของกลาง",
                              [
                                    new ItemsStockBalanceDetail(
                                        "RT08070062000001",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2)
                              ],
                              2),
                    ],
                    [
                          new ItemsStockBalanceType(
                              "รอคืนจากหน่วยงานภายนอก",
                              [
                                    new ItemsStockBalanceDetail(
                                        "RT00107016200008",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "RT00107016200009",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        30,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "RT00107016200010",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "RT00107016200011",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "RT00107016200012",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        2)
                              ],
                              2),
                    ]
                )
            ),
            new ItemsStockMain(
                "คลังเก็บสินค้าในส่วนกลางลำดับ 1",
                new ItemsStockBalance(
                    [
                          new ItemsStockBalanceType(
                              "ของกลางระหว่างคดี",
                              [
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200008",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200009",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        30,
                                        "ลิตร",
                                        3),
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200010",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        1)
                              ],
                              1),
                          new ItemsStockBalanceType(
                              "ของกลางเสร็จสิ้นคดี",
                              [
                                    new ItemsStockBalanceDetail(
                                        "IN00107016200008",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        3)
                              ],
                              2),
                    ],
                    [
                          new ItemsStockBalanceType(
                              "รอขายทอดตลาด",
                              [
                                    new ItemsStockBalanceDetail(
                                        "OU00107016200009",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "OU00107016200010",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        30,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "OU00107016200013",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        1)
                              ],
                              2),
                    ],
                    [
                          new ItemsStockBalanceType(
                              "รอคืนจากหน่วยงานภายนอก",
                              [
                                    new ItemsStockBalanceDetail(
                                        "RT08070062000004",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        20,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "RT00107016200019",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        12,
                                        "ชวด",
                                        30,
                                        "ลิตร",
                                        2),
                                    new ItemsStockBalanceDetail(
                                        "RT00107016200020",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        1),
                                    new ItemsStockBalanceDetail(
                                        "RT00107016200021",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        3),
                                    new ItemsStockBalanceDetail(
                                        "RT00107016200022",
                                        "09 กันยายน 2561",
                                        new ItemsDestroyEvidence(
                                              "สุรา",
                                              "สราแช่",
                                              "ชนิดเบียร์",
                                              "4.4",
                                              "ดีกรี",
                                              "hoegaarden",
                                              "",
                                              "SADLER S PEAKY BLINDER",
                                              0,
                                              "ลิตร",
                                              0,
                                              "",
                                              0,
                                              "",
                                              false,
                                              null,
                                              false,
                                              null,
                                        ),
                                        15,
                                        "ชวด",
                                        40,
                                        "ลิตร",
                                        2)
                              ],
                              2)
                    ]
                )
            ),
      ];*/
  Widget _buildContent(BuildContext context) {
    return Container(
      padding: EdgeInsets.only(bottom: 22.0),
      //margin: EdgeInsets.all(4.0),
      child: ListView.builder(
          itemCount: itemMain.length,
          scrollDirection: Axis.vertical,
          shrinkWrap: true,
          itemBuilder: (BuildContext context, int index) {
            return Container(
              //padding: EdgeInsets.only(top: 2, bottom: 2),
              child: Container(
                padding: EdgeInsets.all(18.0),
                decoration: BoxDecoration(
                    shape: BoxShape.rectangle,
                    border: Border(
                      //top: BorderSide(color: Colors.grey[300], width: 1.0),
                      bottom: BorderSide(color: Colors.grey[300], width: 1.0),
                    )),
                child: ListTile(
                    leading: Padding(
                      padding: paddingLabel,
                      child: Text(
                        (index + 1).toString() + '. ',
                        style: textInputStyleTitle,
                      ),
                    ),
                    title: Padding(
                      padding: paddingLabel,
                      child: Text(
                        itemMain[index].StockName,
                        style: textInputStyleTitle,
                      ),
                    ),
                    trailing: Icon(
                      Icons.arrow_forward_ios,
                      color: Colors.grey[300],
                      size: 18.0,
                    ),
                    onTap: () {
                      Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => StockMainScreenFragment(
                                  ItemsstockMain: itemMain[index],
                                  IsPreview: false,
                                  IsCreate: true,
                                  IsUpdate: false,
                                  Title: itemMain[index].StockName,
                                ),
                          ));
                    }),
              ),
            );
          }),
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        body: Stack(
      children: <Widget>[
        BackgroundContent(),
        Center(
          child: Column(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Container(
                //height: 34.0,
                decoration: BoxDecoration(
                    border: Border(
                  top: BorderSide(color: Colors.grey[300], width: 1.0),
                )),
                /*child: Column(
                  children: <Widget>[Row(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: <Widget>[
                      Padding(
                        padding: EdgeInsets.all(8.0),
                        child: new Text('ILG60_B_12_00_01_00',
                            style: textStylePageName),
                      ),
                    ],
                  ),
                  ],
                )*/
              ),
              Expanded(
                child: _buildContent(context),
              ),
            ],
          ),
        ),
      ],
    ));
  }
}
